// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyjifutrjwaahwtfdmyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5amlmdXRyandhYWh3dGZkbXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzE0NDgsImV4cCI6MjA2OTAwNzQ0OH0.-c8X-9zzCIG9o2jodEzln3fBv2pQRrklHEO0mSsFXW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});